sudo: false
language: php
php:
  - "7.0"
install:
  - composer self-update
  - composer install
script:
  - ./vendor/bin/phpunit
cache:
  directories:
    - $HOME/.composer/cache
matrix:
  fast_finish: true
